### ISSUE TITLE
Installing in Python 3.6 fails

### ISSUE THREAD

**Issue by kwikwag** [simoninireland/simplicial#2]
It seems that the file subdir was left out of the Python 3 repo, as after install I get:

    # pip install simplicial
    ...
    Installing collected packages: simplicial
    Successfully installed simplicial-0.4.3

    # python
    Python 3.6.7 (default, Oct 22 2018, 11:32:17)
    [GCC 8.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import simplicial
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'simplicial'

    # cd 
    /path/to/anaconda3/lib/python3.6/site-packages/simplicial
    # ls
    __init__.py  embedding.py  simplicialcomplex.py
    __pycache__  mtree.py      triangularlattice.py 

I am using Anaconda3 on Ubuntu 18.04.

**Comment by leotrs** [comment]
I get a similar error. `simplicial` installs correctly but can't be imported.

```
$ pip install simplicial
...
Successfully installed ... simplicial-0.4.3 six-1.12.0

$ python
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
>>> import simplicial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leo/.virtualenvs/hyper/lib/python3.5/site-packages/simplicial/__init__.py", line 51, in <module>
    import simplicial.file
ImportError: No module named 'simplicial.file'
```

**Comment by oleg-kachan** [comment]
@kwikwag @leotrs I just commented this line to get it working

**Comment by simoninireland** [comment]
Thanks for the report, I'm fearfully behind with maintaining this code through other commitments -- but I am still working on it :-) I have a development version that's Python3 compatible, and will (hopefully!) get chance to do enough work to release it soon. Thanks for your patience -- Simon

**Comment by leotrs** [comment]
@simoninireland thanks for the update! Looking forward to the next version.

**Comment by saharEldiafy** [comment]
@kwikwag @leotrs hello I think it till not work !! is it work if I use python 2?? or how can I use it ?
and thanks for your efforts @simoninireland

**Comment by simoninireland** [comment]
Think these issues are now fixed: simplicial.file wasn't being included in the distro (through my stupidity), and the Python 2.7  compatibility is now fixed too (I hope).
